// const db = require('./models');

const cityNames = [
  { name: 'Berkeley Lake' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Hitchcock' },
  { name: 'Waynesboro' },
  { name: 'Agua Caliente' },
  { name: 'Horsham' },
  { name: 'Aniwa' },
  { name: 'Axtell' },
  { name: 'Unionville' },
  { name: 'Lake Marcel' },
  { name: 'Upper Falls' },
  { name: 'Wyoming' },
  { name: 'Beaver Meadows' },
  { name: 'Bienville' },
  { name: 'Seco Mines' },
  { name: 'Livonia' },
  { name: 'Coventry' },
  { name: 'Victoria Vera' },
  { name: 'Adairville' },
  { name: 'Mayview' },
  { name: 'Bacavi' },
  { name: 'Drayton' },
  { name: 'Silver Spring' },
  { name: 'Baxley' },
  { name: 'Pinckneyville' },
  { name: 'Elsah' },
  { name: 'Standing Rock' },
  { name: 'Dale' },
  { name: 'Hallettsville' },
  { name: 'Upper Grand Lagoon' },
  { name: 'Grayland' },
  { name: 'Red Cross' },
  { name: 'Two Rivers' },
  { name: 'Dunn Loringx' },
  { name: 'Acomita Lake' },
  { name: 'Pennsbury Village' },
  { name: 'Clayville' },
  { name: 'Woods Landing' },
  { name: 'Lakeshire' },
  { name: 'Meadow' },
  { name: 'Topaz Lake' },
  { name: 'North Henderson' },
  { name: 'Aneth' },
  { name: 'Papaikou' },
  { name: 'Gibbon' },
  { name: 'Ferriday' },
  { name: 'Wilton Center' },
  { name: 'Mescal' },
  { name: 'Sunset Hills' },
  { name: 'Ridgewood' },
  { name: 'Quentin' },
  { name: 'Lares' },
  { name: 'Delaware Water Gap' },
  { name: 'Hobucken' },
  { name: 'Kathryn' },
  { name: 'Algonquin' },
  { name: 'Mulberry Grove' },
  { name: 'Collegedale' },
  { name: 'Silesia' },
  { name: 'Mount Rainier' },
  { name: 'Blades' },
  { name: 'Hindsville' },
  { name: 'Lilydale' },
  { name: 'Leicester' },
  { name: 'South Hills' },
  { name: 'Melbourne Village' },
  { name: 'Lighthouse Point' },
  { name: 'Helper' },
  { name: 'Charlotte Hall' },
  { name: 'Fort Denaud' },
  { name: 'Ben Avon Heights' },
  { name: 'Maunawili' },
  { name: 'Belvedere' },
  { name: 'Roseville' },
  { name: 'Amherst Junction' },
  { name: 'Du Bois' },
  { name: 'East Palatka' },
  { name: 'Waukegan' },
  { name: 'Hungry Horse' },
  { name: 'Buna' },
  { name: 'Toksook Bay' },
  { name: 'Antwerp' },
  { name: 'Tuckahoe' },
  { name: 'Olyphant' },
  { name: 'Bernie' },
  { name: 'Valencia' },
  { name: 'Luxora' },
  { name: 'Faysville' },
  { name: 'Magazine' },
  { name: 'El Reno' },
  { name: 'Buchanan' },
  { name: 'Bryans Road' },
  { name: 'Trinity Center' },
  { name: 'Five Corners' },
  { name: 'Dillwyn' },
  { name: 'Reid Hope King' },
  { name: 'La Fargeville' },
  { name: 'Pimmit Hills' },
  { name: 'Nickerson' },
  { name: 'Paden City' },
  { name: 'Macclenny' },
  { name: 'Leggett' },
  { name: 'Little Browning' },
  { name: 'Llano del Medio' },
  { name: 'Teterboro' },
  { name: 'Tabor' },
  { name: 'Locustdale' },
  { name: 'Munford' },
  { name: 'Ridge' },
  { name: 'Elmwood Place' },
  { name: 'La Bolt' },
  { name: 'Mylo' },
  { name: 'Golf Manor' },
  { name: 'Hurt' },
  { name: 'El Paso' },
  { name: 'Sebring' },
  { name: 'Morse' },
  { name: 'Elk Horn' },
  { name: 'Sheatown' },
  { name: 'Lowndesboro' },
  { name: 'Raywick' },
  { name: 'Blue Ridge Manor' },
  { name: 'Pojoaque' },
  { name: 'Carsonville' },
  { name: 'New Glarus' },
  { name: 'Greenleaf' },
  { name: 'Weskan' },
  { name: 'Sardis' },
  { name: 'Honaunau' },
  { name: 'Freer' },
  { name: 'Paxton' },
  { name: 'North DeLand' },
  { name: 'Maxwell' },
  { name: 'Littleville' },
  { name: 'West Pelzer' },
  { name: 'Chewton' },
  { name: 'Clontarf' },
  { name: 'Metaline' },
  { name: 'Robin Glen' },
  { name: 'Menominee' },
  { name: 'Agra' },
  { name: 'Biggers' },
  { name: 'North Sarasota' },
  { name: 'Crompond' },
  { name: 'Glen Fork' },
  { name: 'Waggaman' },
  { name: 'Los Ybanez' },
  { name: 'South Komelik' },
  { name: 'Valmeyer' },
  { name: 'Dighton' },
  { name: 'West Roy Lake' },
  { name: 'Meadow Lake' },
  { name: 'Moraida' },
  { name: 'Kenhorst' },
  { name: 'Anselmo' },
  { name: 'Greenbelt' },
  { name: 'Spencerport' },
  { name: 'Coto Laurel' },
  { name: 'West Amana' },
  { name: 'Alda' },
  { name: 'Saranac' },
  { name: 'Nora Springs' },
  { name: 'Newland' },
  { name: 'West Milford' },
  { name: 'Ozark' },
  { name: 'Treynor' },
  { name: 'Browntown' },
  { name: 'Central Islip' },
  { name: 'Bow Valley' },
  { name: 'Gobles' },
  { name: 'Luthersville' },
  { name: 'Joppa' },
  { name: 'Chandlerville' },
  { name: 'New Stuyahok' },
  { name: 'Wesley' },
  { name: 'Midway South' },
  { name: 'Ethel' },
  { name: 'Eagle Rock' },
  { name: 'Skellytown' },
  { name: 'Tennant' },
  { name: 'Standard' },
  { name: 'Newington' },
  { name: 'Newcomerstown' },
  { name: 'Vanleer' },
  { name: 'Merriman' },
  { name: 'Redfield' },
  { name: 'West Brownsville' },
  { name: 'McCartys Village' },
  { name: 'Warrensburg' },
  { name: 'Toledo' },
  { name: 'Peeples Valley' },
  { name: 'Thatcher' },
  { name: 'Raytown' },
  { name: 'Paoli' },
  { name: 'Big Lake' },
  { name: 'De Soto' },
  { name: 'Lucas Valley' },
  { name: 'Highland Springs' },
  { name: 'Shelton' },
  { name: 'Grosse Tete' },
  { name: 'Attica' },
];


// cityNames.forEach(c => {
//   db.agency
//     .create({
//       name: c.name,
//     })
//     .then(result => {
//       console.log(result.agency.name);
//     });
// });

// db.user.findOne({
//   where: { id: 1 },
// }).then((test) => {
//   // by using eager loading, the article model should have a comments key
//   console.log(test.dataValues);
// })
